### ISSUE TITLE
HEDA Settings default Affiliation Mappings list disappears after update to Summer 16

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#269] opened 2016-06-13 21:54 UTC
In an org where the default list of Affiliation Mappings had been available (Academic Program, Business Organization, Household Account, Educational Institution, University Department, Sports Organization), after update to Summer '16 the list is no longer visible in the UI

The same is true of the list of Reciprocal Settings

![screen shot 2016-06-13 at 2 53 47 pm](https://cloud.githubusercontent.com/assets/204643/16024440/b5b3511a-3176-11e6-9167-e6140e1565bb.png)

**Comment by ceiroa** [comment] 2016-06-14 14:59
Duplicate of #268.

**Closed by ceiroa** 2016-06-14 14:59 UTC
Labels: bug
