### ISSUE TITLE
HEDA Settings Save not Working

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/HEDAP#388] opened 2017-01-31 22:39 UTC
After HEDA is installed, the Account Model field (under System tab) is blank. If you edit the page and try to save, it looks like it works. But after refreshing the value isn't there. 

Same happens with other values, like the "Account record type that supports Household Addresses" option under HEDA Settings > Accounts and Contacts.

Found in HEDA 1.27. Likely regression.

**Comment by ceiroa** [comment] 2017-01-31 22:39
**lurch: add

**Comment by LurchTheButler** [comment] 2017-01-31 22:40
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004poynAAA" target="_blank">W-017655</a>

**Comment by chrismcmahon** [comment] 2017-01-31 22:53
That's odd because I see saving these Settings working in my dev org running 1.27 (Beta 4). 

I have automated tests for these that pass, and I verified that Save for Settings works manually as well by changing the Setting, reloading the page, and navigating back to see the changed Setting.

**Comment by ceiroa** [comment] 2017-01-31 23:01
I only see the issue if the setting is initially blank. Once it's set, changes seem to work. Very odd. Mike had the same problem in his org.

**Comment by chrismcmahon** [comment] 2017-01-31 23:03
Odd that those settings are initially blank also, I don't think I've seen that before.

**Comment by davidjray** [comment] 2017-02-01 17:45
Carlos and I did some investigation and we were able to identify the root of the issue. 

The "Default Account Model" select field in HEDA settings is a custom drop down component. When using managed code with Locker Service enabled and the field in the Hierarchy Settings is blank the value is not sent in the payload to the server when selected and the settings are saved.

**Comment by davidjray** [comment] 2017-02-08 20:37
After more investigation this is caused by two things in managed code with locker service enabled:
1. When the install script does not run basic settings configuration is not completed. We had a release (1.27) that didn't run the install script.
2. A known Locker Service bug prevented binding to blank values in the hierarchical settings object in the HEDA settings component. 

The fix for the known issue is scheduled for release soon. We'll keep this issue open to remind us to test this once the fix has been released.

For now, the workaround is to temporarily disable Locker Service if you need to save any settings this bug prevented you from saving.

**Comment by annejackson** [comment] 2018-03-05 17:23
Checked with @davidjray on this as well. According to the work item in GUS it looks like the Locker Service issue has been fixed. I also can not duplicate this issue. David and Carlos/Dylan also see it fine to close this issue. Closing.

**Closed by annejackson** 2018-03-05 17:23 UTC
Labels: accepted, bug
