### ISSUE TITLE
TDTM Manager mergeToken method excludes Filter Field and Filter Value fields

### ISSUE THREAD

**Issue by davidjray** [SalesforceFoundation/HEDAP#467] opened 2017-07-19 17:02 UTC
Issue identified by [Brian Petersen (Queen's School of Business) ](https://powerofus.force.com/_ui/core/userprofile/UserProfilePage?u=0058000000ABNmU) 
PUB Thread: https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000D6uj&fId=0D58000003WhXZw

Issue: When using the TDTM_Global_API.setTdtmConfig method to manage TDTM configuration the Filter Field and Filter Value fields are not set.

Steps to reproduce:
1. Run TDTM_Global_API.setTdtmConfig in the anonymous apex window with a configuration that includes a value for the Filter Field and Filter Value fields in some of the items.
2. After running the code note the values in the Filter Field and Filter Value fields were not copied over.

As stated in the PUB post by Brian, the root of the problem is most likely the TDTM_Manager.mergeToken method excluding those fields.

**Comment by davidjray** [comment] 2017-07-19 17:02
**lurch: add

**Comment by LurchTheButler** [comment] 2017-07-19 17:05
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007O8rbAAC" target="_blank">W-019597</a>

**Comment by jacebryan** [comment] 2017-09-08 19:28
Closing this Issue as a duplicate of #465

**Comment by weizsforg** [comment] 2017-11-07 23:03
Hi @jacebryan , I see you closed this issue and merge it with #465. Is there any specific reason to merge it to #465? I think this issue is a separate issue.

**Comment by ceiroa** [comment] 2017-11-08 15:52
It's actually a different issue from #465. I will reopen it.

**Closed** 2017-11-29 21:02 UTC
Labels: accepted

**Comment by mrbelvedere** [comment] 2017-11-29 21:30
Included in beta release 1.45 (Beta 3)

**Comment by mrbelvedere** [comment] 2017-11-30 18:55
Included in production release rel/1.45
